---
- name: "Move oracle repository to the /tmp dir"
  shell: mv /etc/yum.repos.d/{{ ol_repo_file }} /tmp

- name: "Move RPM-GPG-KEY-oracle to the /tmp dir"
  shell: mv /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle /tmp

- name: "Yum clean all"
  command: yum clean all
  args:
     warn: no

- name: "Remove Oracle zipfile "
  file:
    path: /opt/install/"{{ item }}"
    state: absent
  with_items:
    - "{{ installer_archives }}"

#- name: notify telegram users
#  telegram:
#    token: "bot278308776:AAG4OF9vo5HZpqdoVGZe6YIbOBl-oDBNgSQ"
#    chat_id: 254827606
#    msg: Ansible Task has been finished successfully. Result= {{ result|succeeded }}{{ hello.stdout }}{{ hello.stderr }}
