---
- name: "Move oracle repository to the /tmp dir"
  shell: mv /etc/yum.repos.d/public-yum-ol6.repo /tmp

- name: "Move RPM-GPG-KEY-oracle to the /tmp dir"
  shell: mv /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle /tmp

- name: "Yum clean all"
  command: yum clean all
  args:
     warn: no

- name: "Remove Oracle zipfile "
  file:
    path: "/opt/install/{{ installer_archives }}" 
    state: absent
