--- 
# ==> Configure Linux 
#- name: "Install required libraries" 
#  yum: 
#    name: "{{ item }}"
#    state: present 
#  with_items: packages_list
 
#- name: "Disable SELinux" 
#  selinux: 
#     state: disabled
 
#- name: "Disable Firewall Deamon (firewalld)"
#  service: 
#    name: firewalld
#    state: stopped
#    enabled: no 
#

- pause:
    prompt: "Make sure Database is not in Production"
- name: "ATTENTION!!! Delete Old database"
  become: true
  become_user: oracle
  become_method: su
  shell: "{{ oracle_db_home }}/bin/dbca -silent -deleteDatabase -sourceDB {{ oracle_db_name }}"
  ignore_errors: true

- name: "ATTENTION!!! Remove old Oracle, dbora and links"
  shell: rm -rf "{{ item }}"
  with_items:
      - /etc/oraInst.loc
      - /opt/db/oraInventory
      - /opt/db/*
      - /etc/init.d/dbora
      - /etc/rc.d/rc3.d/S98dbora
      - /etc/rc.d/rc3.d/K01dbora
      - /etc/rc.d/rc5.d/S98dbora
      - /etc/rc.d/rc5.d/K01dbora
      - /opt/db/oracle*
  args:
     warn: no

- name: "Install an additional OS packages"
  yum:
     pkg: "{{ item }}"
     state: present
     update_cache: yes
  with_items:
     - "{{ add_packages }}"

- name: "Add oracle repository"
  template:
    src: "{{ ol_repo_file }}"
    dest: /etc/yum.repos.d/{{ ol_repo_file }}
    owner: root
    group: root
    mode: 0644

- name: "Copy and install RPM-GPG-KEY-oracle"
  template:
    src: "{{ RPM_GPG_KEY_oracle }}"
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle

- name: "Install dependencies"
  yum:
     pkg: "{{ item }}"
     state: present
     update_cache: yes
  with_items:
    - "{{ oracle_dependencies }}"
  ignore_errors: true

#-----------------------------------------------------------------

# ==> Create users and groups
- name: "Create groups"
  group: 
     name: "{{ oracle_group }}"
     state: present

- name: "Add extra groups"
  group: 
     name: "{{ item }}"
     state: present
  with_items: 
     - "{{ oracle_dba_group }}"
     - "{{ oracle_oper_group }}"

- name: "Create user"
  user: 
     name: "{{ oracle_user }}"
     group: "{{ oracle_group }}"
     password: "{{ oracle_pass }}"

- name: "Add extra groups"
  user: 
     name: "{{ oracle_user }}" 
     groups: "{{ item }}"
     append: yes
  with_items: 
     - "{{ oracle_dba_group }}"
     - "{{ oracle_oper_group }}"

- name: "Change {{ oracle_user }}  password"
  shell: echo "{{ oracle_pass }}" | passwd "{{ oracle_user }}" --stdin

#---------------------------------------------------

- name: "Create ORA_HOME dir" 
  shell: ORA_HOME="{{ oracle_path }}"
- file:  
     path: "{{ oracle_db_home }}"  
     state: directory
     recurse: yes 
     owner: oracle 
     group: oinstall 

- name: "Swapon"
  shell: swapon -a

- name: "Create Backup dir"
  file:
     path: /backups
     state: directory
     recurse: yes
     owner: oracle
     group: oinstall

- name: "Add the oraInst.loc"
  template: 
     src: oraInst.loc
     dest: /etc/oraInst.loc
     owner: oracle
     group: dba
     mode: 0640

- name: "Add oracle bash_profile"
  template:
    src: bash_profile.j2
    dest: /home/oracle/.bash_profile
    owner: oracle
    group: dba
    mode: 0640

- name: "Configure the 'bash_oracle' file" 
  lineinfile:  
     dest: /home/oracle/.bash_profile
     regexp: ^ORACLE_SID=me  
     line: ORACLE_SID={{ oracle_db_name }}
     backup: yes 

#---------------------------------------------

- name: "Add the 'dbora' config files"
  template:
    src: dbora.j2
    dest: /etc/init.d/dbora
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int==6

- name: "enable 'dbora' script to run at startup"
  shell: chkconfig --add dbora 
  when: ansible_distribution_major_version|int==6
- shell: ln -s /etc/init.d/dbora /etc/rc.d/rc3.d/S98dbora
  when: ansible_distribution_major_version|int==6
- shell: ln -s /etc/init.d/dbora /etc/rc.d/rc3.d/K01dbora
  when: ansible_distribution_major_version|int==6
- shell: ln -s /etc/init.d/dbora /etc/rc.d/rc5.d/S98dbora
  when: ansible_distribution_major_version|int==6
- shell: ln -s /etc/init.d/dbora /etc/rc.d/rc5.d/K01dbora
  when: ansible_distribution_major_version|int==6

- name: "Add the 'dbora.service' config files"
  template:
    src: dbora.service
    dest: /lib/systemd/system/dbora.service
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int==7

- name: "enable 'dbora' script to run at startup"
  shell: systemctl enable dbora.service
  when: ansible_distribution_major_version|int==7

- name: "Copy start_all.sh"
  template:
    src: start_all.sh
    dest: /home/oracle/start_all.sh
    owner: oracle
    group: dba
    mode: 0744
  when: ansible_distribution_major_version|int==7

- name: "Copy stop_all.sh"
  template:
    src: stop_all.sh
    dest: /home/oracle/stop_all.sh
    owner: oracle
    group: dba
    mode: 0744
  when: ansible_distribution_major_version|int==7
