---
#
# "Create database" another example
#  shell: "{{ oracle_db_home }}/bin/dbca -silent -createDatabase -templateName General_Purpose.dbc \
#     -gdbname {{ oracle_db_name }} -sid {{ oracle_db_name }} -sysPassword {{ oracle_db_syspass }} \
#     -systemPassword {{ oracle_db_system }} -dbsnmpPassword {{ oracle_db_dbsnmp }} -responseFile NO_VALUE \
#     -characterSet {{ oracle_characterSet }} -memoryPercentage {{ oracle_memoryPercentage }} -emConfiguration LOCAL"

# ==> generate response file
- name: "Gerenerate the response file for software only installation"
  template:
     src: dbca.rsp
     dest: /tmp/dbca.rsp
     owner: oracle
     group: oinstall
     mode: 0644

# ==> execute installation
- name: "Create Database"
  become: true
  become_user: oracle
  become_method: su
  shell: /opt/db/oracle/product/11g/bin/dbca -createDatabase -responseFile /tmp/dbca.rsp -silent

- name: "Update oratab for autostart"
  replace: 
     dest: /etc/oratab 
     regexp: "{{ oracle_db_name }}:{{ oracle_db_home }}:N"
     replace: "{{ oracle_db_name }}:{{ oracle_db_home }}:Y" 
     backup: yes

- name: "Check if database is running"
  shell: ps -ef |grep pmon |grep -v grep
  tags:
   - psout
  register: psout
  ignore_errors: true
