---
- name: "Listener | Create responsefile for listener configuration"
  template: 
     src: netca.rsp 
     dest: "/opt/install/netca.rsp"

- name: "Listener | Create listener"
  shell: "{{ oracle_db_home }}/bin/netca -responseFile /opt/install/netca.rsp -silent"
  become: true
  become_user: oracle
  become_method: su
