---

- name: "Add the 'dbora.service' config files"
  template:
    src: dbora.service
    dest: /tmp/dbora.service
    owner: root
    group: root
    mode: 0655
  when: ansible_distribution_major_version|int==6
