CREATE TABLESPACE TBSUN4_TABLES
DATAFILE '/opt/db/oracle/oradata/un4/TBS_SUN4TBL.OBF'
SIZE 1000M
AUTOEXTEND ON NEXT 128K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TEMPORARY TABLESPACE TBSUN4_TEMP
TEMPFILE '/opt/db/oracle/oradata/un4/TBS_SUN4TEMP.OBF'
SIZE 200M
AUTOEXTEND ON NEXT 640K
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE TABLESPACE TBSUN4_CM
DATAFILE '/opt/db/oracle/oradata/un4/TBS_SUN4CM.OBF'
SIZE 200M
AUTOEXTEND ON NEXT 128K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE TBSUN4_SYSTABLES
DATAFILE '/opt/db/oracle/oradata/un4/TBS_SUN4SYST.OBF'
SIZE 100M
AUTOEXTEND ON NEXT 128K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE TBSUN4_IND
DATAFILE '/opt/db/oracle/oradata/un4/TBS_SUN4IND.OBF'
SIZE 1000M
AUTOEXTEND ON NEXT 128K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE TBSUN4_IND_CM
DATAFILE '/opt/db/oracle/oradata/un4/TBS_SUN4IND_CM.OBF'
SIZE 500M
AUTOEXTEND ON NEXT 128K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

exit
